# Generated by Django 3.2.7 on 2022-03-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isstaffcategory',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
