# Generated by Django 3.2.7 on 2022-03-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0003_alter_isstaffcategory_isdelete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isstaffcategorybyuser',
            name='isStaff',
        ),
        migrations.RemoveField(
            model_name='isstaffcategorybyuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='IsStaffCategory',
        ),
        migrations.DeleteModel(
            name='IsStaffCategoryByUser',
        ),
    ]
