# Generated by Django 3.2.7 on 2022-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.IntegerField(max_length=10)),
                ('isOtp', models.IntegerField(max_length=6)),
                ('msgStatus', models.BooleanField(blank=True, null=True)),
                ('msgId', models.CharField(blank=True, max_length=500, null=True)),
                ('isVerify', models.BooleanField(default=False)),
                ('maxTry', models.IntegerField(blank=True, default=1, null=True)),
                ('isBlockNumber', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
