# Generated by Django 3.2.7 on 2022-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverify',
            name='isOtp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otpverify',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
