# Generated by Django 3.2.7 on 2022-03-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220306_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='Profile.png', null=True, upload_to='profile-images'),
        ),
    ]
