# Generated by Django 3.2.7 on 2022-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220309_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile-images/Profile.png', null=True, upload_to='profile-images'),
        ),
    ]
