# Generated by Django 3.2.7 on 2022-03-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientName', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('isAppointmentDone', models.CharField(blank=True, default='Panding', max_length=225, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfDrug', models.CharField(blank=True, max_length=225, null=True)),
                ('drug', models.CharField(blank=True, max_length=225, null=True)),
                ('stengh', models.CharField(blank=True, max_length=225, null=True)),
                ('instructions', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(blank=True, max_length=500, null=True)),
                ('diseaseDiscription', models.TextField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, max_length=225, null=True)),
                ('frequncy', jsonfield.fields.JSONField(default=dict)),
                ('duration', models.CharField(blank=True, max_length=225, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dose', models.TextField(blank=True, null=True)),
                ('doseTime', models.TextField(blank=True, null=True)),
                ('beforeDrug', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.appointment')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.drug')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription', models.ManyToManyField(blank=True, to='patient.Prescription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientGroupByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientGroup', models.ManyToManyField(blank=True, to='patient.PatientGroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('whichProof', models.CharField(blank=True, max_length=500, null=True)),
                ('proofId', models.CharField(blank=True, max_length=500, null=True)),
                ('mobileNo', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=400, null=True)),
                ('state', models.CharField(blank=True, max_length=400, null=True)),
                ('country', models.CharField(blank=True, max_length=400, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('problem', models.CharField(blank=True, max_length=500, null=True)),
                ('problemDescription', models.TextField(blank=True, null=True)),
                ('patientImage', models.ImageField(blank=True, default='patient-images/avtar.png', null=True, upload_to=None)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('patientGroupId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PatientByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient', models.ManyToManyField(blank=True, to='patient.PatientDetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment', models.ManyToManyField(to='patient.Appointment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientdetails'),
        ),
    ]
