# Generated by Django 3.2.7 on 2022-03-25 19:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionbyuser',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescriptionbyuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='drug',
            name='stengh',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionByUser',
        ),
    ]
