# Generated by Django 3.2.7 on 2022-03-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20220325_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='instructions',
        ),
    ]
