# Generated by Django 3.2.7 on 2022-03-09 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_auto_20220309_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='patientImage',
            field=models.ImageField(blank=True, null=True, upload_to=patient.models.user_directory_path_main),
        ),
        migrations.CreateModel(
            name='PatientByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ManyToManyField(to='patient.PatientDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
