# Generated by Django 3.2.7 on 2022-03-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_drug_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
