# Generated by Django 3.2.7 on 2022-03-26 22:09

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_delete_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescriptionDetails', jsonfield.fields.JSONField(default=dict)),
                ('status', models.CharField(blank=True, default='approve', max_length=225, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.appointment')),
            ],
        ),
    ]
