# Generated by Django 3.2.7 on 2022-03-10 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patientdetails_patientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TestMany',
        ),
        migrations.DeleteModel(
            name='TestOne',
        ),
    ]
