# Generated by Django 3.2.7 on 2022-03-10 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20220310_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isstaffcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
