# Generated by Django 3.2.7 on 2022-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20220326_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientgroupbyuser',
            name='patientGroup',
        ),
        migrations.RemoveField(
            model_name='patientgroupbyuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='patientGroupId',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='PatientGroup',
        ),
        migrations.DeleteModel(
            name='PatientGroupByUser',
        ),
    ]
