# Generated by Django 3.2.7 on 2022-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20220327_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
