# Generated by Django 3.2.7 on 2022-03-10 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_isstaffcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbyuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
