# Generated by Django 3.2.7 on 2022-03-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_patientbyuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbyuser',
            name='patient',
            field=models.ManyToManyField(blank=True, null=True, related_name='patient', to='patient.PatientDetails'),
        ),
    ]
