# Generated by Django 3.2.7 on 2022-03-11 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0010_alter_patientbyuser_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(blank=True, max_length=500, null=True)),
                ('diseaseDiscription', models.TextField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientbyuser',
            name='patient',
            field=models.ManyToManyField(blank=True, to='patient.PatientDetails'),
        ),
        migrations.CreateModel(
            name='PatientGroupByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientGroup', models.ManyToManyField(blank=True, to='patient.PatientGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientbyuser',
            name='patientGroupByUser',
            field=models.ManyToManyField(blank=True, to='patient.PatientGroupByUser'),
        ),
    ]
