# Generated by Django 3.2.7 on 2022-03-11 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0011_auto_20220311_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbyuser',
            name='patientGroupByUser',
        ),
        migrations.AddField(
            model_name='patientbyuser',
            name='patientGroup',
            field=models.ManyToManyField(blank=True, to='patient.PatientGroup'),
        ),
        migrations.AlterField(
            model_name='patientbyuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientgroupbyuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
