# Generated by Django 3.2.7 on 2022-03-11 03:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20220311_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbyuser',
            name='patientGroup',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
