# Generated by Django 3.2.7 on 2022-03-11 04:42

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_patientbyuser_patientgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patientImage',
            field=models.ImageField(default='patient-images/avtar.png', upload_to=patient.models.user_directory_path_main),
        ),
    ]
