# Generated by Django 3.2.7 on 2022-03-11 11:34

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_patientdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='my_images',
            field=models.ImageField(blank=True, default='patient-images/avtar.png', null=True, upload_to=patient.models.user_directory_path_main),
        ),
    ]
