# Generated by Django 3.2.7 on 2022-03-11 11:50

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20220311_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='my_images_one',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='pa_img',
            field=models.ImageField(default='patient-images/avtar.png', upload_to=patient.models.user_directory_path_main),
        ),
    ]
