# Generated by Django 3.2.7 on 2022-03-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_auto_20220311_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='pa_img',
        ),
    ]
