# Generated by Django 3.2.7 on 2022-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_remove_patientdetails_pa_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='patientImage',
            field=models.ImageField(blank=True, default='patient-images/avtar.png', null=True, upload_to=None),
        ),
    ]
