# Generated by Django 3.2.7 on 2022-03-15 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0025_auto_20220314_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isstaffcategory',
            old_name='isStaff',
            new_name='accessType',
        ),
        migrations.RemoveField(
            model_name='isstaffcategory',
            name='user',
        ),
        migrations.AddField(
            model_name='isstaffcategory',
            name='email',
            field=models.EmailField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='isstaffcategory',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='isstaffcategory',
            name='thisIs',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='isstaffcategory',
            name='userName',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='IsStaffCategoryByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isStaff', models.ManyToManyField(to='patient.IsStaffCategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
