# Generated by Django 3.2.7 on 2022-03-15 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0026_auto_20220315_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isstaffcategory',
            name='email',
        ),
        migrations.AddField(
            model_name='isstaffcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='IsStaffCategoryByUser',
        ),
    ]
