# Generated by Django 3.2.7 on 2022-03-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_appointment_appointmentbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isAppointmentDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
