# Generated by Django 3.2.7 on 2022-03-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_auto_20220319_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDuration',
        ),
    ]
