# Generated by Django 3.2.7 on 2022-03-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0033_remove_appointment_appointmentduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='timeFrom',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='timeTo',
            new_name='startDate',
        ),
    ]
