# Generated by Django 3.2.7 on 2022-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0034_auto_20220320_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
