# Generated by Django 3.2.7 on 2022-03-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0035_appointment_patientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='isAppointmentDone',
            field=models.CharField(blank=True, default='Panding', max_length=225, null=True),
        ),
    ]
