# Generated by Django 3.2.7 on 2022-03-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0036_auto_20220323_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfDrug', models.CharField(blank=True, max_length=225, null=True)),
                ('drug', models.CharField(blank=True, max_length=225, null=True)),
                ('stengh', models.CharField(blank=True, max_length=225, null=True)),
                ('instructions', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, max_length=225, null=True)),
                ('frequncy', models.JSONField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=225, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dose', models.TextField(blank=True, null=True)),
                ('doseTime', models.TextField(blank=True, null=True)),
                ('beforeDrug', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.appointment')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.drug')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription', models.ManyToManyField(blank=True, to='patient.Prescription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
