# Generated by Django 3.2.7 on 2022-03-24 09:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0037_drug_prescription_prescriptionbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='frequncy',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
