# Generated by Django 3.2.7 on 2022-03-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0038_alter_prescription_frequncy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='frequncy',
            new_name='the_json',
        ),
    ]
