# Generated by Django 3.2.7 on 2022-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='state',
            field=models.ManyToManyField(to='micro_api.State'),
        ),
        migrations.AddField(
            model_name='state',
            name='city',
            field=models.ManyToManyField(to='micro_api.City'),
        ),
    ]
